### ISSUE TITLE
SDL 2 macOS

### ISSUE THREAD

**Issue by MCES10** [phoboslab/wipeout-rewrite#99]
When compiling this on my apple silicon mac it says I need sdl2 which I installed via homebrew. I have tried countless tutorials on youtube issues on stackoverflow questions in reddit and more but still cannot fix the issue.

**Comment by Noialia** [comment]
same here

**Comment by shy-neon** [comment]
I'm experiencing the same issue on build

**Comment by MCES10** [comment]
should i try it on a Intel mac ?

**Comment by shy-neon** [comment]
Give it a shot i doubt the platform matters, but who knows

**Comment by phoboslab** [comment]
The cmake route is broken for me on macOS, too. Sadly, I don't know much about cmake. Maybe @The-King-of-Toasters can help?
```
~/projects/wipeout-rewrite/src/platform_sdl.c:1:10: fatal error: 'SDL2/SDL.h' file not found
```

For what it's worth, the "old" way to build with just `make` still works just fine on my M2.

```bash
cd wipeout-rewrite/
make
```

**Comment by MCES10** [comment]
I tried it on my Intel Mac and your solution but still get this error on both. `/Users/MCES10/Desktop/wipeout-rewrite/src/platform_sdl.c:1:10: fatal error: 'SDL2/SDL.h' file not found
#include <SDL2/SDL.h>
         ^~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/wipeout.dir/src/platform_sdl.c.o] Error 1
make[1]: *** [CMakeFiles/wipeout.dir/all] Error 2
make: *** [all] Error 2
`

**Comment by shy-neon** [comment]
using make instead of make lead to a successful build but as soon as it is executed I get: 
`Abort at "src/utils.c" line 23: Could not open file for reading: ./wipeout-rewrite-master/wipeout/textures/drfonts.cmp`
there is not such file nor a texture folder

**Comment by jordie-sound-system** [comment]
Trying to run this on macOS Catalina and getting the same error as above...has anyone come closer to a solution?

**Comment by jordie-sound-system** [comment]
> How did you install SDL2? Maybe this helps? https://stackoverflow.com/questions/20277477/how-do-you-include-files-in-c-from-the-library-framework-folder-in-mac
> 
> Did you try the old makefile?
> 
> ```shell
> cd wipeout-rewrite/
> make
> ```

This ended up working after updating my GLEW library. Everything working perfectly with the exception of music :)

**Comment by shinra-electric** [comment]
The include needs to be changed from `#include <SDL2/SDL.h>` to `#include <SDL.h>`

**Comment by MCES10** [comment]
Easy fix Do Not put the wipeout track files that are compiled use the ones mentioned here https://phoboslab.org/log/2023/08/rewriting-wipeout in Phoboslab's article at the end.

**Comment by lordfeck** [comment]
@phoboslab FWIW I get the same error:

```
[  3%] Building C object CMakeFiles/wipeout.dir/src/platform_sdl.c.o
/Users/lordfeck/src_notmine/wipeout-rewrite/src/platform_sdl.c:1:10: fatal error: 'SDL2/SDL.h' file not found
#include <SDL2/SDL.h>
         ^~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/wipeout.dir/src/platform_sdl.c.o] Error 1
make[1]: *** [CMakeFiles/wipeout.dir/all] Error 2
make: *** [all] Error 2

```

When following the instructions and using cmake to build on MacOS Sonoma 14.5, Apple Silicon. My exact invocation was:

```
cmake -S ./ -B ./build  -DCMAKE_PREFIX_PATH="$(brew --prefix sdl2)"
cmake --build ./build  
```

However, I _could_ build the game using the classic Makefile. I'd suggest either updating the Readme to reflect this, or if you want I could investigate and try to get the Cmake file working on my system.

**Comment by shinra-electric** [comment]
> /Users/lordfeck/src_notmine/wipeout-rewrite/src/platform_sdl.c:1:10: fatal error: 'SDL2/SDL.h' file not found

> However, I _could_ build the game using the classic Makefile. I'd suggest either updating the Readme to reflect this, or if you want I could investigate and try to get the Cmake file working on my system.

The include in `src/platform_sdl.c` needs to be changed from `#include <SDL2/SDL.h>` to `#include <SDL.h>`

**Comment by lordfeck** [comment]
@shinra-electric tyvm. that indeed fixes it. I'd suggest the following diff to handle OSX better:
```
--- a/src/platform_sdl.c
+++ b/src/platform_sdl.c
@@ -1,4 +1,8 @@
+#ifdef __APPLE__
+#include <SDL.h>
+#else
 #include <SDL2/SDL.h>
+#endif
```
will open a PR if phobos agrees, or even just makes the change himself

**Comment by phoboslab** [comment]
It should actually be just `#include "SDL.h"` on all platforms according to https://nullprogram.com/blog/2023/01/08/ _Mistake 2: Including SDL2/SDL.h_

I used that in high_impact ([here](https://github.com/phoboslab/high_impact/blob/master/src/platform_sdl.c#L3)) and it works well, but requires `sdl2-config --cflags` in the [makefile](https://github.com/phoboslab/high_biolab/blob/master/Makefile#L189). I'll change it when I find the muse or if anyone wants to send a PR :)

**Comment by lordfeck** [comment]
I'll try that fix and get one up tomorrow, so I can tell my friends I've technically contributed code to Wipeout ;)
